### ISSUE TITLE
html/template: "index" is undefined Error

### ISSUE THREAD

**Issue by eiffelqiu** [gernest/utron#43]
I clone the todo webapp sample code and replace postgres  to  mysql ,  i made the same directory structure and filename, when i run the web app,  the database output the correct result, but it reports that it could not find the index.html template , app.yml  is also correct ,  when i change view_dir  to other name(not 'views') , the app will stop running,  so i do not know where i got wrong?

any help will be appreciated.

project structure

```
│  .gitignore
│  doc.go
│  info.exe
│  main.go
│
├─config
│      app.yml
│
├─controllers
│      todo.go
│
├─models
│      todo.go
│
├─static
│      todo.css
│
└─views
        index.html
```

```yaml
app_name: utron web app
base_url: http://localhost:5000
port: 5000
verbose: true
static_dir: static
view_dir: views
database: "mysql"
database_conn: "svc:svc@/services?charset=utf8"
```

```go
func (t *Todo) Home() {
	todos := []*models.Todo{}
	t.Ctx.DB.Order("created_at desc").Find(&todos)
	fmt.Println("%+v", todos[0])
	t.Ctx.Data["List"] = todos
	t.Ctx.Template = "index"
	t.HTML(http.StatusOK)
}
```

```
2016/01/06 10:21:38 >>INFO>> starting server at http://localhost:5000
%+v &{1 23423423 0001-01-01 00:00:00 +0000 UTC 0001-01-01 00:00:00 +0000 UTC}
2016/01/06 10:21:45 >>ERR>> html/template: "index" is undefined
```
